#include <iostream>
#include <iomanip>
#include <cstdint>
#include <string>
#include <vector>

#include "Vaes_top.h"
#include "verilated.h"
#include "verilated_vcd_c.h"
#include "vectors.h" // Generated by Python

vluint64_t main_time = 0;
std::vector<uint32_t> current_hw_key(8, 0xFFFFFFFF);

void tick(Vaes_top* dut, VerilatedVcdC* tfp) {
    dut->clk = 0; dut->eval(); if (tfp) tfp->dump(main_time); main_time += 5;
    dut->clk = 1; dut->eval(); if (tfp) tfp->dump(main_time); main_time += 5;
}

bool load_key(Vaes_top* dut, VerilatedVcdC* tfp, const uint32_t* new_key) {
    bool match = true;
    for(int i=0; i < (KEY_BITS/32); i++) if(current_hw_key[i] != new_key[i]) match = false;
    if (match) return true;

    int k_words = KEY_BITS / 32;
    for (int i = 0; i < k_words; i++) {
        dut->key_in[k_words - 1 - i] = new_key[i];
        current_hw_key[i] = new_key[i];
    }
    dut->key_load = 1; tick(dut, tfp); dut->key_load = 0;
    int timeout = 0;
    while (!dut->key_ready && timeout++ < 500) tick(dut, tfp);
    return (timeout < 500);
}

void run_aes_step(Vaes_top* dut, VerilatedVcdC* tfp, uint32_t* data, bool decrypt) {
    if (decrypt) {
        for (int i = 0; i < 4; i++) dut->i_ciphertext[3 - i] = data[i];
        dut->dec_start = 1; tick(dut, tfp); dut->dec_start = 0;
        while (!dut->dec_done) tick(dut, tfp);
        for (int i = 0; i < 4; i++) data[i] = dut->o_plaintext[3 - i];
    } else {
        for (int i = 0; i < 4; i++) dut->i_plaintext[3 - i] = data[i];
        dut->enc_start = 1; tick(dut, tfp); dut->enc_start = 0;
        while (!dut->enc_done) tick(dut, tfp);
        for (int i = 0; i < 4; i++) data[i] = dut->o_ciphertext[3 - i];
    }
}

int main(int argc, char** argv) {
    Verilated::commandArgs(argc, argv);
    Verilated::traceEverOn(true);
    Vaes_top* dut = new Vaes_top;
    VerilatedVcdC* tfp = new VerilatedVcdC;
    
    // Note: Tracing to VCD is slow for MCT. Set to NULL to disable for speed.
    dut->trace(tfp, 99); 
    tfp->open("sim_output.vcd");

    // Reset
    dut->rst_n = 0; tick(dut, tfp); tick(dut, tfp);
    dut->rst_n = 1; tick(dut, tfp);

    int pass_count = 0;
    for (int i = 0; i < NUM_VECTORS; i++) {
        const TestVector& v = vectors[i];
        std::string name(v.name);
        bool is_dec = (name.find("Dec") != std::string::npos);
        bool is_mct = (name.find("[MCT]") != std::string::npos);

        load_key(dut, tfp, v.key);
        
        uint32_t buffer[4];
        for(int j=0; j<4; j++) buffer[j] = is_dec ? v.ct[j] : v.pt[j];

        // Core Loop: 1000 for MCT samples, 1 for KAT/MMT
        int iterations = is_mct ? 1000 : 1;
        for(int j=0; j < iterations; j++) {
            run_aes_step(dut, tfp, buffer, is_dec);
        }

        bool match = true;
        const uint32_t* expected = is_dec ? v.pt : v.ct;
        for(int j=0; j<4; j++) if(buffer[j] != expected[j]) match = false;

        if (match) {
            pass_count++;
            std::cout << "PASS: " << name << std::endl;
        } else {
            std::cout << "FAIL: " << name << std::endl;
        }
    }

    std::cout << "\nResults: " << pass_count << "/" << NUM_VECTORS << " passed." << std::endl;
    tfp->close(); delete dut; return 0;
}
